### ISSUE TITLE
failed to bild

### ISSUE THREAD

**Issue by pici** [BrockReece/vue-kanban#1]
installed via npm to my quasar projekt and ran quasar dev.
Build process failed with:
Module build failed: Error: Couldn't find preset "env" relative to directory ....

Any hints ?

brgds

**Comment by BrockReece** [comment]
Hi,

Sorry I have never used quasar before, how did you set up your quasar project and I will try to replicate the issue?

Cheers
Brock

**Comment by BrockReece** [comment]
Ah, try adding babel-preset-env with npm/yarn to your quasar project.
That worked for me.

**Comment by pici** [comment]
Great. This did it for me as well. 
Thx a lot. 
Brgds pici
