### ISSUE TITLE
Installation Problem 

### ISSUE THREAD

**Issue by donPuerto** [BrockReece/vue-kanban#2]
Any idea?
![image](https://user-images.githubusercontent.com/9329005/30479123-607a02cc-9a46-11e7-95b0-f71fcd6c5f7f.png)

**Comment by BrockReece** [comment]
It looks like your user doesn't have access to rename the folder `node_modules/vue`

What version of Vue are you using? The only thing I can think is that this package requires a different version of Vue than what you are using, but this feels more like a symptom than the cause.

**Comment by donPuerto** [comment]
I just solved the problem. npm 5.4.1 is a buggy version i switch t 5.4.2

**Comment by donPuerto** [comment]
Also :) I was not able to run it on Vue. I'm using Vue CLI and Vuetify framework. Since it is "scss" I convert it to normal CSS...
![image](https://user-images.githubusercontent.com/9329005/30484841-3cb68032-9a5e-11e7-82db-f319becb343c.png)

**Comment by BrockReece** [comment]
Ah ok, if you install sass-loader and node-sass it should have been able to handle the scss in your project.

Glad it is working for you now though.

**Comment by donPuerto** [comment]
I did install everything but still got this,
![image](https://user-images.githubusercontent.com/9329005/30735898-300dbc56-9fb3-11e7-8a74-26f404edbb79.png)
