### ISSUE TITLE
Template or render function not defined.

### ISSUE THREAD

**Issue by demonmind** [BrockReece/vue-kanban#3]
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <KanbanBoard>
       <CanvasKanban> at app/assets/javascripts/components/app/campaigns/canvas/kanban/canvas-kanban.vue
         <App> at app/assets/javascripts/components/app/app.vue
           <Root>
Template:

```
<template>
  <div v-if="loaded" class="kanban">
    <canvas-header></canvas-header>
    <kanban-board :stages="stages" :blocks="blocks"
      @update-flight-status="updateFlightStatus">
      <div v-for="block in blocks">
        <div>
          <strong>id:</strong> {{ block.id }}
        </div>
        <div>
          {{ block.title }}
        </div>
      </div>
    </kanban-board>
  </div>
  <full-loader v-else></full-loader>
</template>
```

Am i doing anything wrong?

**Comment by BrockReece** [comment]
Hey, which version of vue-loader are you using?

**Comment by demonmind** [comment]
"vue-loader": "^13.0.4",

**Comment by BrockReece** [comment]
Ah ok, it looks like there has been a breaking change to `require` statements in v13 of vue-loader.
I will fix it later today.

Thanks for pointing this out.

**Comment by BrockReece** [comment]
I have just published a new version to NPM which should fix this.
Can you let me know?

**Comment by demonmind** [comment]
Yep looks like it works for now. Will update if i have any issues when i dive deeper.

**Comment by BrockReece** [comment]
Awesome. Thanks :)

**Comment by demonmind** [comment]
@BrockReece now I am getting another error:

[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'pointerEnabled' of undefined"

**Comment by demonmind** [comment]
Just the structure, nevermind
