### ISSUE TITLE
Invalid default value for prop "config": Props with type Object/Array must use a factory function to return the default value.

### ISSUE THREAD

**Issue by alexsantm2019** [BrockReece/vue-kanban#38]
Hi guys,
I have installed vue-kanban, however, I had this error in console:

Invalid default value for prop "config": Props with type Object/Array must use a factory function to return the default value.

Could you help me?
Thanks in advanced

**Comment by BrockReece** [comment]
Ah this is a bug, I will fix and release a new version. Thanks for raising.

**Comment by BrockReece** [comment]
Should be fixed in vue-kanban@1.6.0
