### ISSUE TITLE
add order by id

### ISSUE THREAD

**Issue by vahidalvandi** [BrockReece/vue-kanban#4]
hi , how i order block in list with change orderid parametr?

**Comment by BrockReece** [comment]
Hi, you can order the blocks array however you like before passing it through to the kanban component? I would probably use a computed value in my parent component. 

Hope that helps?

**Comment by vahidalvandi** [comment]
i need save orderid each block in each stage after darg and drop

**Comment by BrockReece** [comment]
Ah, I see, sorry I misunderstood.
I will see what I can do.

**Comment by BrockReece** [comment]
Ok, that should fix it.
The `update-block` event now returns the zero based index of the block as the third argument.
Do you want to test this before I publish a new version to npm?

**Comment by BrockReece** [comment]
I'm going to assume that this fixed your issue and close this.

**Comment by enricribas** [comment]
an array of ids in order would be easier. Or the id that was moved and the position it took. Otherwise, it's pretty hard to calculate the new order. Just a thought
