### ISSUE TITLE
why animation in darg in other stage faild?

### ISSUE THREAD

**Issue by vahidalvandi** [BrockReece/vue-kanban#5]
when drag a block in other stage animation not work...
because update stage parameter !!!

why?

i cant find any solution after 2 day work!

**Comment by BrockReece** [comment]
I am guessing this is to do with the way data flows from parent the child. I will look into it, any chance you could share what you have tried over those two days though so we aren't covering the same ground?

**Comment by BrockReece** [comment]
I have managed to fix the animation by debouncing the updateBlock method. 

https://github.com/BrockReece/vue-kanban/commit/8d60b132fb9d328ed67e896270ebde5b7d08b012#diff-ea994a51b0d9884f4fc046eca11a5c99R49

**Comment by BrockReece** [comment]
I'm going to assume that this fixed your issue and close this.
