### ISSUE TITLE
It's not very clear how you use the config (dragula) option 

### ISSUE THREAD

**Issue by kairos0ne** [BrockReece/vue-kanban#56]
{
  config: {
    // Don't allow blocks to be moved out of the approved stage
    accepts(block, target, source) {
      return source.dataset.status !== 'approved',
    }
  }
}

Where do you specify this config and how do you parse it to the component ?

**Comment by BrockReece** [comment]
Oh sorry, maybe the docs aren't clear enough, but the config options can be passed into the Kanban component as a prop. Assuming your `config` options are defined in the data method of the parent component, you can pass the config to the component like so...

```html
<kanban-board :config="config" />
```

**Comment by kairos0ne** [comment]
Thanks that's perfect
